---
title: "baseline_chla"
output: html_document
---

The purpose of this markdown is meant to create a baseline chl-a model across the 
mainstem of the CLP.

```{r}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, error = FALSE)
library(readxl)
library(here)
library(mgcv)
library(Metrics)
library(sf)
library(nhdplusTools)
library(mapview)
library(tidyverse)

version_date = Sys.Date()
```

# Chlorophyll-a Grab Samples

```{r}
# grab chemistry data - this is from the zenodo pull
ross_chla <- read_csv(here("data/upper_clp_dss/ross_clp_chem/data/cleaned/CLP_chemistry_up_to_20250701.csv")) %>% 
  rename(site_name = Site,
         date = Date) %>% 
  select(site_code, site_name = site_name, date = date,
         ChlA, Field_DO_mgL, Field_Temp_C, 
         distance_upstream_km, Lat:location_type, -watershed) %>% 
  mutate(collector = "ROSS",
         doy = yday(date),
         location_type = factor(location_type)) %>% 
  filter(!is.na(ChlA)) %>% 
  filter(Field_DO_mgL < 40) # remove the oddball in do

ggplot(ross_chla, aes(x = yday(date), y = ChlA)) +
  geom_point()+
  facet_grid(location_type ~ .)

plot(ross_chla %>% select(ChlA, Field_DO_mgL, Field_Temp_C))
```

```{r}
walk(unique(ross_chla$location_type), function(loc) {
  gg <- ross_chla %>% 
    filter(location_type == loc) %>% 
    ggplot(. , aes(x = yday(date), y = ChlA, color = factor(year(date)))) +
    geom_point() +
    facet_wrap(site_name ~ ., scales = "free_y")
  print(gg)
})

```

# Calculate distance from closest reservoir

```{r}
# Poudre HUC
huc8 <- get_huc(id="10190007", type = "huc08")
mapview(huc8)

# Pull all NHDPlusV2 flowines within Poudre Watershed
flowlines <- get_nhdplus(AOI = huc8, realization = "flowline", t_srs = 4326)
mapview(flowlines)

# Grab all waterbodies
waterbodies <- get_waterbodies(AOI = huc8, t_srs = 4326)
mapview(waterbodies)
# filter to those intersecting with flowlines
waterbodies <- waterbodies[flowlines, ]
mapview(waterbodies)

# Pull in site coordinates
xy <- ross_chla %>%
  select(site_code, site_name, Lat, Long, Campaign, location_type) %>% 
  distinct() %>% 
  st_as_sf(coords=c('Long','Lat'), crs=4326) 
mapview(flowlines) + mapview(waterbodies) + mapview(xy)

# Find NHD comid for each coordinate. NOTE: resolution not great for some sites (see Comanche/Hourglass
# complex)... Some samples are along the same flowline, and are therefore represented with the same
# information. 
distance_upstream_waterbody <- pmap_dfr(list(comid = xy$comid, geom = xy$geometry, site_code = xy$site_code),
         function(comid, geom, site_code) {
           # get flowlines upstream of point
           upstream_of_point <- get_UT(flowlines, comid)
           # and grab those as a sf
           upstream_fl <- get_nhdplus(comid = upstream_of_point) %>% 
             get_tocomid(., add = TRUE) %>%
             mutate(ID=comid, toID=tocomid, length=lengthkm)
           # filter waterbodies for those that intersect the fl
           upstream_wb <- waterbodies[upstream_fl, ] %>% 
             filter(onoffnet == 1)
           # if there is at least one wb upstream, calculate the distance
           if(nrow(upstream_wb) >= 1) {
             art_path_outlet <- map_dfr(.x = upstream_wb$comid,
                                        ~ tryCatch(get_wb_outlet(.x, upstream_fl),
                                                   error = function(e) {} ))
             end_point <- get_node(art_path_outlet) %>% 
               mutate(comid = art_path_outlet$comid)
             mapview(upstream_wb) + mapview(end_point) + mapview(geom)
             distance <- get_pathlength(upstream_fl) %>% 
               rename(comid = ID) %>% 
               right_join(end_point, by = "comid") %>% 
               arrange(pathlength) %>% 
               first() %>% 
               mutate(site_code = site_code) %>% 
               select(site_code, dist_to_up_wb_km = pathlength)
           } else {
             distance <- tibble("site_code" = site_code, "dist_to_up_wb_km" = NA)
           }
           distance
         })

```

distance from reservoir - adapt from zenodo pub for distance upstream
https://github.com/rossyndicate/CLP_waterchem_data/blob/v2025.07.01/scripts/distance_finder.R


```{r}
distance_to_major_trib <- function(site) {
  flowline <- get_nhdplus(AOI = xy %>% filter(site_code == site))
  mainstem <- get_UM(flowlines, flowline$comid)
  mainstem_fl <- get_nhdplus(comid = mainstem) %>% 
    get_tocomid(., add = TRUE) %>%
    mutate(ID=comid, toID=tocomid, length=lengthkm,
           perc_change = ((totdasqkm -  flowline$totdasqkm) / flowline$totdasqkm) * 100) %>%
    select(comid, ID, toID, length, perc_change)
  mainstem_big_trib <- mainstem_fl %>%
    filter(perc_change <= -20) %>%
    select(comid, perc_change) %>%
    filter(perc_change == max(perc_change, na.rm = TRUE))
  trib_fl <- get_nhdplus(comid = tribs) %>%
    get_tocomid(., add = TRUE) %>%
    mutate(ID=comid, toID=tocomid, length=lengthkm,
           perc_change = ((totdasqkm -  flowline$totdasqkm) / flowline$totdasqkm) * 100) %>%
    select(comid, ID, toID, length, perc_change)
  if(nrow(mainstem_big_trib) >= 1) {
    distance <- get_pathlength(mainstem_fl) %>% 
      filter(ID == mainstem_big_trib$comid) %>%
      pull(pathlength)
  } else {
    distance <- NA
  }

  # mapview(mainstem_big_trib, color = "red") + mapview(trib_fl) + mapview(mainstem_fl %>% filter(comid != mainstem_big_trib$comid), zcol = "perc_change") 

  meta <- xy %>% filter(site_code == site) %>%
    mutate(dist_to_maj_trib = distance)
  return(meta)
}
distance_meta <- xy$site_code %>%
    map(~distance_to_major_trib(.))
```

watershed area:reservoir area

```{r}

chl_model<- gam(log(ChlA) ~ s(doy, bs = "cc", by = location_type) + Field_Temp_C + Field_DO_mgL + location_type, method = "REML", data = ross_chla)
gam.check(chl_model)
summary(chl_model)
AIC(chl_model)

par(mfrow = c(1, 1))
plot(chl_model, pages = 1, shade = TRUE, seWithMean = TRUE)
```

```{r}
ross_chla_less <- ross_chla %>% 
  filter(!location_type %in% c("Inflow", "Stream", "Outflow") & Campaign %in% c("Chambers Complex", "Mainstem - Upper"))
chl_model_no_inflow <- gam(log(ChlA) ~ s(doy, bs = "cc", by = location_type) + Field_Temp_C + Field_DO_mgL + location_type, method = "REML", data = ross_chla_less)
gam.check(chl_model_no_inflow)
summary(chl_model_no_inflow)
AIC(chl_model_no_inflow)

par(mfrow = c(1, 1))
plot(chl_model_no_inflow, pages = 1, shade = TRUE, seWithMean = TRUE)
```

```{r}
ross_chla_target <- ross_chla %>% 
  filter(site_code %in% c("PBD", "PMAN", 
                          "PBR", "PFAL")) %>% 
  mutate(site_code = factor(site_code))

chl_model_target <- gam(log(ChlA) ~ s(doy, bs = "cc", by = site_code) + 
                          Field_DO_mgL +
                          site_code, 
                        method = "REML", 
                        data = ross_chla_target,
                        select = TRUE)
gam.check(chl_model_target)
summary(chl_model_target)
concurvity(chl_model_target, full = T)
AIC(chl_model_target)
plot(chl_model_target, all.terms =T, pages = 1)

par(mfrow = c(1, 1))
plot(chl_model_target, pages = 1, shade = TRUE, seWithMean = TRUE)


# Build new data grid for predictions
newdat <- ross_chla_target %>%
  summarize(doy = seq(min(ross_chla_target$doy), max(ross_chla_target$doy), by = 1),
            Field_Temp_C = mean(Field_Temp_C, na.rm = TRUE),
            Field_DO_mgL = mean(Field_DO_mgL, na.rm = TRUE),
            distance_upstream_km = first(distance_upstream_km),
            .by = site_code)

# Predict from model
preds <- predict(chl_model_target, newdata = newdat, se.fit = TRUE)
newdat <- newdat %>%
  mutate(fit = exp(preds$fit),
         se = exp(preds$se.fit),
         upper = fit + 2 * se,
         lower = fit - 2 * se)

# Plot
ggplot(newdat, aes(x = doy, y = (fit), color = site_code, fill = site_code)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.2, color = NA) +
  labs(x = "Day of Year", y = "Predicted Chlorophyll a", 
       title = "Seasonal chlorophyll patterns by location type") +
  theme_minimal(base_size = 14)

```

