---
title: "Colocation differences"
author: "Sam Struthers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load all packages and themes
source("src/setup_libraries.R")

```

Re run workflow design prior to this to load `data/sensors/uclp_sensor_raw.parquet` as needed

## Load raw data

```{r}
list.files(path = here("data", "upper_clp_dss" , "sensor"), pattern = ".parquet", full.names = T)

all_data_raw <- read_parquet("data/upper_clp_dss/sensor/uclp_sensor_raw_2025-03-26_2025-07-09.parquet")

```

## Load in sample data

```{r}

  
  water_chem <- read_parquet("data/upper_clp_dss/modeling/ROSS_FC_water_chemistry.parquet")%>%
  mutate(DT_round_MT = with_tz(round_date(DT_sample, unit = "1 hour" ), tz = "America/Denver"))%>%
  rename(site = site_code)%>%
  select(site, DT_round_MT, ChlA, SC, lab_turb)

#toc_max <- max(water_chem$TOC, na.rm = T)

```

# Comparison Plots

```{r}
subset <- all_data_raw %>% 
  filter(!is.na(mean),
         site %in% c("pbr", "pbr_fc"),
         parameter %nin% c("FDOM Fluorescence", "ORP", "Depth"))%>%
  mutate(site = ifelse(site == "pbr", "PBR ROSS", "PBR FC"))

parameters = unique(subset$parameter)
plot_list <- list()


units_table <- data.frame(parameter = c("Turbidity", "pH", "ChlA", "Specific Conductivity", "DO", "Temperature"),
                            units = c("NTU", "pH", "RFU", "uS/cm", "mg/L", "C"), 
                          param_w_units = c("Turbidity (NTU)", "pH", "ChlA (RFU)", "Specific Conductivity (uS/cm)", "DO (mg/L)", "Temperature ( C )"))

for(param in parameters){
  
  param_units <- units_table$param_w_units[units_table$parameter == param]
  
  data_plot <- ggplot(subset%>%filter(parameter == param), aes(x = DT_round_MT, y = mean, color = site)) +
        geom_line()+
    #TODO: add in grab samples as "truth" for SC, Turb, pH and chla (may want to normalize chla before hand)
         # geom_point(data = plot_water_chem,
         #     aes(x = DT_round, y = TOC, shape = collector, color = "Sample Values")) +
        labs(
             x = "Date",
             y = param_units, 
             color = "Site")+
    scale_color_manual(values = ROSS_lt_pal)+
    ROSS_theme

  comp_data <- subset %>%
  pivot_wider(id_cols = c(parameter, DT_round_MT), 
              names_from = site, 
              values_from = mean) %>%
  mutate(difference =  `PBR ROSS`- `PBR FC`,
         percent_difference = (`PBR ROSS`- `PBR FC`) / `PBR FC` * 100, 
         cat = case_when(percent_difference > 0 ~  "PBR ROSS > PBR FC", 
                         percent_difference < 0 ~ "PBR ROSS < PBR FC", 
                         percent_difference == 0 ~ "Equal",
                         is.na(percent_difference) ~ "No Data"))
  
  comp_plot_abs <- ggplot(comp_data%>%filter(parameter == param), aes(x = DT_round_MT, y = difference, color = cat)) +
    geom_point() +
    geom_hline(yintercept = 0, linetype = "solid", color = "black") +
    labs(title = paste("Comparison of PBR ROSS and PBR FC", param),
         x = "", 
         y = paste0("Absolute Difference for ", param_units), 
         color = "Difference Category") +
    scale_color_manual(values = ROSS_acc_pal)+
    ROSS_theme
  
  comp_plot_perc <- ggplot(comp_data%>%filter(parameter == param), aes(x = DT_round_MT, y = percent_difference, color = cat)) +
    geom_point() +
    geom_hline(yintercept = 0, linetype = "solid", color = "black") +
    labs(x = "Date",
         y = paste0("Percent Difference for ", param ), 
         color = "Difference Category") +
    scale_color_manual(values = ROSS_acc_pal)+
    ROSS_theme
      
  plot_list[[param]] <- data_plot+ comp_plot_abs+ comp_plot_perc +
                                   plot_layout(ncol = 3, nrow = 1, 
                                    guides = "collect")
  
  
}

print(plot_list)
      

ggsave("data/upper_clp_dss/figures/ROSS_FC_turb_comparison.png", 
       plot = plot_list$Turbidity,
       width = 10, height = 6, units = "in", dpi = 300)
ggsave("data/upper_clp_dss/figures/ROSS_FC_temp_comparison.png", 
       plot = plot_list$Temperature,
       width = 10, height = 6, units = "in", dpi = 300)
ggsave("data/upper_clp_dss/figures/ROSS_FC_ph_comparison.png", 
       plot = plot_list$pH,
       width = 10, height = 6, units = "in", dpi = 300)

ggsave("data/upper_clp_dss/figures/ROSS_FC_sc_comparison.png", 
       plot = plot_list$`Specific Conductivity`,
       width = 10, height = 6, units = "in", dpi = 300)
```
